const $ = (id) => document.getElementById(id);
const contactAvatar=$("contactAvatar"),contactName=$("contactName"),contactStatus=$("contactStatus"),messagesContainer=$("messagesContainer");
const messageForm=$("messageForm"),messageInput=$("messageInput"),sendButton=$("sendButton"),attachmentButton=$("attachmentButton"),fileInput=$("fileInput");
const contactDetailsButton=$("contactDetailsButton"),moreButton=$("moreButton"),profileModal=$("profileModal"),profileModalAvatar=$("profileModalAvatar");
const profileModalName=$("profileModalName"),profileModalPhone=$("profileModalPhone"),profileModalAbout=$("profileModalAbout"),profileModalUsername=$("profileModalUsername");
const replyBar=$("replyBar"),replyText=$("replyText"),cancelReply=$("cancelReply"),clearChatButton=$("clearChatButton");
const attachmentMenu=$("attachmentMenu"),sendContactButton=$("sendContactButton"),contactShareModal=$("contactShareModal"),shareContactName=$("shareContactName"),shareContactPhone=$("shareContactPhone"),shareContactError=$("shareContactError"),confirmShareContact=$("confirmShareContact");
const activeConversation=ChatFlow.getStoredJSON("chatFlowActiveConversation",null),profile=ChatFlow.getStoredJSON("chatFlowProfile",null);
let messages=[],socket=null,replyingTo=null,typingTimer=null;
if(!ChatFlow.getToken()||!activeConversation?.id||!activeConversation.contact) window.location.replace("chats.html");
const contact=activeConversation.contact;
contactAvatar.textContent=ChatFlow.getInitials(contact.fullName); contactName.textContent=contact.fullName||contact.phone;
if(contact.photo){contactAvatar.style.backgroundImage=`url(${contact.photo})`;contactAvatar.textContent="";}
function formatTime(v){return new Date(v).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"});}
function formatLastSeen(v){if(!v)return "Offline";const d=new Date(v);return `Last seen ${d.toLocaleDateString([],{day:"2-digit",month:"short"})} at ${formatTime(v)}`;}
function setPresence(online,lastSeen){contactStatus.textContent=online?"Online":formatLastSeen(lastSeen||contact.lastSeen);contactStatus.classList.toggle("online",online);}
async function loadPresence(){try{const p=await ChatFlow.api(`/users/${contact.id}/presence`);setPresence(p.online,p.lastSeen);}catch{setPresence(false,contact.lastSeen);}}
function statusText(m){if(m.senderId!==profile?.id)return "";if(m.readAt)return "✓✓";if(m.deliveredAt)return "✓✓";return "✓";}
function summary(m){return m.type==="TEXT"?(m.text||""):m.type==="IMAGE"?"Image":m.type==="CONTACT"?(m.contactName||"Contact"):(m.fileName||"File");}
function beginReply(m){replyingTo=m;replyText.textContent=summary(m).slice(0,80);replyBar.hidden=false;messageInput.focus();}
function createMessageElement(m){
 const row=document.createElement("div"),bubble=document.createElement("div"),meta=document.createElement("div"),time=document.createElement("time"),status=document.createElement("span");
 row.className=`message-row ${m.senderId===profile?.id?"sent":"received"}`; row.dataset.messageId=m.id;bubble.className="message-bubble";meta.className="message-meta";time.className="message-time";status.className=`message-status ${m.readAt?"read":""}`;
 if(m.replyTo){const r=document.createElement("button");r.type="button";r.className="reply-preview";r.innerHTML=`<small>Reply</small><span>${ChatFlow.escapeHTML(summary(m.replyTo))}</span>`;bubble.appendChild(r);}
 if(m.type==="IMAGE"&&m.fileUrl){const img=document.createElement("img");img.className="message-image";img.src=m.fileUrl;img.alt=m.fileName||"Shared image";img.onclick=()=>window.open(m.fileUrl,"_blank");bubble.appendChild(img);}
 else if((m.type==="PDF"||m.type==="FILE")&&m.fileUrl){const a=document.createElement("a");a.className="file-card";a.href=m.fileUrl;a.target="_blank";a.rel="noopener";a.innerHTML=`<span>📄</span><span><strong>${ChatFlow.escapeHTML(m.fileName||"File")}</strong><small>${m.fileSize?Math.ceil(m.fileSize/1024)+" KB":"Open file"}</small></span>`;bubble.appendChild(a);}
 else if(m.type==="CONTACT"){const card=document.createElement("div");card.className="contact-card-message";card.innerHTML=`<div class="contact-card-avatar">${ChatFlow.getInitials(m.contactName)}</div><div><strong>${ChatFlow.escapeHTML(m.contactName||"Contact")}</strong><p>${ChatFlow.escapeHTML(m.contactPhone||"")}</p><a href="tel:${encodeURIComponent(m.contactPhone||"")}">Call</a></div>`;bubble.appendChild(card);}
 else {const text=document.createElement("p");text.className="message-text";text.textContent=m.text;bubble.appendChild(text);}
 const actions=document.createElement("div");actions.className="message-actions";actions.innerHTML=`<button type="button" data-action="reply">↩</button><button type="button" data-action="delete">🗑</button>`;actions.querySelector("[data-action=reply]").onclick=()=>beginReply(m);actions.querySelector("[data-action=delete]").onclick=async()=>{if(!confirm("Delete this message for you?"))return;try{await ChatFlow.api(`/conversations/${activeConversation.id}/messages/${m.id}`,{method:"DELETE"});messages=messages.filter(x=>x.id!==m.id);renderMessages(false);}catch(e){alert(e.message);}};bubble.appendChild(actions);
 time.textContent=formatTime(m.createdAt);status.textContent=statusText(m);meta.append(time,status);bubble.append(meta);row.appendChild(bubble);return row;
}
function renderMessages(scroll=true){messagesContainer.innerHTML='<div class="date-chip">Today</div>';messages.forEach(m=>messagesContainer.appendChild(createMessageElement(m)));if(scroll)requestAnimationFrame(()=>messagesContainer.scrollTop=messagesContainer.scrollHeight);}
async function markRead(){try{await ChatFlow.api(`/conversations/${activeConversation.id}/read`,{method:"POST",body:"{}"});}catch{}}
async function loadMessages(){try{const data=await ChatFlow.api(`/conversations/${activeConversation.id}/messages`);messages=data.messages;renderMessages();await markRead();}catch(e){alert(e.message);window.location.replace("chats.html");}}
function connectRealtime(){if(typeof io!=="function")return;socket=io({auth:{token:ChatFlow.getToken()}});socket.emit("conversation:join",activeConversation.id);
 socket.on("message:new",async m=>{if(m.conversationId!==activeConversation.id)return showIncomingNotice("New message in another chat.");if(!messages.some(x=>x.id===m.id)){messages.push(m);renderMessages();if(m.senderId!==profile?.id)await markRead();}});
 socket.on("messages:read",data=>{if(data.conversationId!==activeConversation.id)return;messages=messages.map(m=>m.senderId===profile?.id?{...m,deliveredAt:m.deliveredAt||data.readAt,readAt:data.readAt}:m);renderMessages(false);});
 socket.on("presence:update",p=>{if(p.userId===contact.id)setPresence(p.online,p.lastSeen);});socket.on("typing:update",p=>{if(p.conversationId===activeConversation.id&&p.userId===contact.id)contactStatus.textContent=p.typing?"Typing...":formatLastSeen(contact.lastSeen);});socket.on("connect_error",()=>{contactStatus.textContent="Connection unavailable";});}
function openProfileModal(){profileModalAvatar.textContent=ChatFlow.getInitials(contact.fullName);profileModalName.textContent=contact.fullName||"ChatFlow User";profileModalPhone.textContent=contact.phone||"";profileModalAbout.textContent=contact.about||"Available on ChatFlow";profileModalUsername.textContent=contact.username?`@${contact.username}`:"Not set";if(contact.photo){profileModalAvatar.style.backgroundImage=`url(${contact.photo})`;profileModalAvatar.textContent="";}profileModal.classList.add("open");profileModal.setAttribute("aria-hidden","false");}
function closeProfileModal(){profileModal.classList.remove("open");profileModal.setAttribute("aria-hidden","true");}
function showIncomingNotice(text){let n=$("incomingNotice");if(!n){n=document.createElement("button");n.id="incomingNotice";n.type="button";n.className="incoming-notice";n.onclick=()=>window.location.href="chats.html";document.body.appendChild(n);}n.textContent=`${text} Open chats`;n.classList.add("show");clearTimeout(n.hideTimer);n.hideTimer=setTimeout(()=>n.classList.remove("show"),4500);}
async function sendMessage(){const text=messageInput.value.trim();if(!text)return;sendButton.disabled=true;const original=text;messageInput.value="";messageInput.style.height="auto";replyingTo=null;replyBar.hidden=true;try{const data=await ChatFlow.api(`/conversations/${activeConversation.id}/messages`,{method:"POST",body:JSON.stringify({text,replyToId:replyingTo?.id||null})});if(!messages.some(m=>m.id===data.message.id)){messages.push(data.message);renderMessages();}}catch(e){messageInput.value=original;alert(`Message not sent: ${e.message}`);}finally{sendButton.disabled=!messageInput.value.trim();}}
async function uploadFile(file){const form=new FormData();form.append("file",file);attachmentMenu.classList.remove("open");try{const data=await ChatFlow.api(`/uploads/${activeConversation.id}`,{method:"POST",body:form});if(!messages.some(m=>m.id===data.message.id)){messages.push(data.message);renderMessages();}}catch(e){alert(e.message);}finally{fileInput.value="";}}
async function sendContact(){const contactName=shareContactName.value.trim(),contactPhone=ChatFlow.normalizeIndianPhone(shareContactPhone.value);if(!contactName||!/\+?[0-9]{10,15}/.test(contactPhone)){shareContactError.textContent="Enter a valid name and phone number.";return;}try{const data=await ChatFlow.api(`/conversations/${activeConversation.id}/contact`,{method:"POST",body:JSON.stringify({contactName,contactPhone})});if(!messages.some(m=>m.id===data.message.id)){messages.push(data.message);renderMessages();}contactShareModal.classList.remove("open");shareContactName.value="";shareContactPhone.value="";}catch(e){shareContactError.textContent=e.message;}}
messageForm.addEventListener("submit",e=>{e.preventDefault();sendMessage();});messageInput.addEventListener("input",()=>{if(socket){socket.emit("typing:start",activeConversation.id);clearTimeout(typingTimer);typingTimer=setTimeout(()=>socket.emit("typing:stop",activeConversation.id),900);}messageInput.style.height="auto";messageInput.style.height=`${Math.min(messageInput.scrollHeight,130)}px`;sendButton.disabled=!messageInput.value.trim();});
messageInput.addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();sendMessage();}});cancelReply.onclick=()=>{replyingTo=null;replyBar.hidden=true;};clearChatButton.onclick=async()=>{if(!confirm("Clear this chat for you?"))return;try{await ChatFlow.api(`/conversations/${activeConversation.id}/clear`,{method:"POST",body:"{}"});messages=[];renderMessages(false);}catch(e){alert(e.message);}};contactDetailsButton.onclick=openProfileModal;moreButton.onclick=openProfileModal;profileModal.querySelectorAll("[data-close-profile]").forEach(el=>el.onclick=closeProfileModal);
attachmentButton.onclick=()=>attachmentMenu.classList.toggle("open");document.querySelectorAll("[data-file-type]").forEach(btn=>btn.onclick=()=>{fileInput.accept=btn.dataset.fileType==="image"?"image/jpeg,image/png,image/webp":"application/pdf";fileInput.click();});fileInput.onchange=()=>fileInput.files[0]&&uploadFile(fileInput.files[0]);
sendContactButton.onclick=()=>{attachmentMenu.classList.remove("open");contactShareModal.classList.add("open");};document.querySelectorAll("[data-close-contact-share]").forEach(el=>el.onclick=()=>contactShareModal.classList.remove("open"));confirmShareContact.onclick=sendContact;
window.addEventListener("focus",markRead);sendButton.disabled=true;loadPresence();loadMessages();connectRealtime();
